[package]
name = "reminders"
version = "0.1.0"
authors = ["Eric Davis <edavis@insanum.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.11"
yaml-rust = "0.4"
regex = "1"
chrono = "0.4"
lazy_static = "1.3.0"
getopts = "0.2"
